apiVersion: v2
name: pagopa-shared-platform-authorizer
description: Microservice handling authorization caching for the Authorizer system
type: application
version: 0.88.0
appVersion: 0.2.3
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
